# eslint configuration
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  jasmine: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'angular'
#globals:
plugins:
  - angular
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always